name : CoderCo Custom Action

description: Greet someone

inputs:
  who-to-greet: 
    description: Who to greet
    required: true
    default: 'hello'

outputs:
  time:
    description: time greeted

runs:
  using: node20
  main: dist/index.js